services:
  - type: web
    name: okr-slack-bot
    env: node
    plan: free
    buildCommand: npm ci --production=false
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
    autoDeploy: true